# Generated by Django 5.1.4 on 2024-12-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
